name = "Red Lounge"
description = "A clean, responsive, template with red accents."
license = "Apache 2.0"
licenselink = "https://github.com/fredbsc/hugo-redlounge/blob/master/LICENSE.md"
source_repo = "https://github.com/fredbsc/hugo-redlounge"
homepage = "https://github.com/fredbsc/hugo-redlounge"
tags = ["redlounge", "red", "raleway", "libre baskerville", "blog", "gallery"]
features = ["blog", "gallery"]
min_version = 0.14

[author]
    name = "Tom Maiaroto"
    homepage = "http://www.shift8creative.com"
